// 샘플 작품 (학년·교과 다양, 1개는 exe-link). 서명은 tools/build-sample.mjs가 붙인다.
const page = (title, body, script) =>
  `<!doctype html><html lang="ko"><meta charset="utf-8"><title>${title}</title>` +
  `<body style="font-family:sans-serif;padding:12px">${body}<script>${script}</script></body></html>`;

export const works = [
  {
    id: 'sample-fraction-pizza',
    title: '분수 피자 게임',
    type: 'html',
    grade: '초4',
    subject: '수학',
    standard: '[4수01-12]',
    audience: 'student',
    author: '푸른 혹등고래 · 초등',
    howToUse: '피자 조각을 눌러 주어진 분수만큼 색칠해 보세요.',
    promptRecipe: '4학년 분수 도입용 피자 나누기 게임을 만들어 줘. 조각을 누르면 색이 바뀌고 분수가 표시돼.',
    version: 1,
    addedAt: '2026-09-20T00:00:00Z',
    html: page('분수 피자', '<h3>분수 피자</h3><p id="t">8조각 중 0조각</p><button id="b">조각 추가</button>',
      'let n=0;document.getElementById("b").onclick=()=>{n=Math.min(8,n+1);document.getElementById("t").textContent="8조각 중 "+n+"조각 ("+n+"/8)"}'),
  },
  {
    id: 'sample-times-quiz',
    title: '구구단 번개 퀴즈',
    type: 'html',
    grade: '초4',
    subject: '수학',
    standard: '[4수01-05]',
    audience: 'student',
    author: '노을 고래 · 초등',
    howToUse: '문제를 보고 답을 입력한 뒤 확인을 누르세요.',
    promptRecipe: '구구단 문제를 무작위로 내고 정답이면 칭찬해 주는 퀴즈를 만들어 줘.',
    version: 1,
    addedAt: '2026-09-22T00:00:00Z',
    html: page('구구단 퀴즈', '<p id="q"></p><input id="a" type="number" aria-label="답"><button id="c">확인</button><p id="r"></p>',
      'let x,y;function nq(){x=2+Math.floor(Math.random()*8);y=2+Math.floor(Math.random()*8);document.getElementById("q").textContent=x+" × "+y+" = ?"}nq();document.getElementById("c").onclick=()=>{document.getElementById("r").textContent=+document.getElementById("a").value===x*y?"정답!":"다시 해 봐요";nq()}'),
  },
  {
    id: 'sample-mult-cards',
    title: '곱셈 연습 카드',
    type: 'html',
    grade: '초4',
    subject: '수학',
    standard: '[4수01-07]',
    audience: 'student',
    author: '새벽 고래 · 초등',
    howToUse: '카드를 눌러 뒤집으며 곱셈을 연습하세요.',
    promptRecipe: '곱셈 연습용 뒤집기 카드를 만들어 줘.',
    version: 1,
    addedAt: '2026-09-25T00:00:00Z',
    html: page('곱셈 카드', '<div id="c" style="padding:24px;border:1px solid #888;cursor:pointer">12 × 3 (눌러서 정답 보기)</div>',
      'document.getElementById("c").onclick=function(){this.textContent="36"}'),
  },
  {
    id: 'sample-water-states',
    title: '물의 상태 변화 관찰',
    type: 'html',
    grade: '중1',
    subject: '과학',
    standard: '[9과03-02]',
    audience: 'student',
    author: '바다빛 고래 · 중등',
    howToUse: '슬라이더로 온도를 바꿔 물의 상태를 관찰하세요.',
    promptRecipe: '온도 슬라이더로 물의 고체·액체·기체 상태가 바뀌는 시뮬레이터를 만들어 줘.',
    version: 1,
    addedAt: '2026-09-27T00:00:00Z',
    html: page('물의 상태', '<input id="s" type="range" min="-20" max="120" value="20" aria-label="온도"><p id="o"></p>',
      'const s=document.getElementById("s"),o=document.getElementById("o");function u(){const t=+s.value;o.textContent=t+"℃ : "+(t<=0?"고체(얼음)":t<100?"액체(물)":"기체(수증기)")}s.oninput=u;u()'),
  },
];

export const exeItems = [
  {
    id: 'sample-exe-coding-tool',
    title: '블록 코딩 연습 도구 (설치형)',
    type: 'exe-link',
    grade: '중1',
    subject: '정보',
    standard: '[9정01-01]',
    audience: 'teacher',
    author: '은빛 고래 · 중등',
    howToUse: '교사 PC에 설치한 뒤 수업 시연에 사용합니다.',
    version: 1,
    addedAt: '2026-09-28T00:00:00Z',
    url: 'https://example.com/downloads/block-coding.exe',
    sourceRepo: 'https://example.com/source/block-coding',
    sha256: 'a'.repeat(64),
    scanResult: '샘플: 검사 통과 (테스트 데이터)',
    environment: 'Windows 10 이상',
  },
];
