// 샘플 작품 (수업·업무, 학년·교과 다양, 1개는 EXE). 서명은 tools/build-sample.mjs가 붙인다.
// 분류: domain(수업/업무) → category → subcategory → tags
const page = (title, body, script) =>
  `<!doctype html><html lang="ko"><meta charset="utf-8"><title>${title}</title>` +
  `<body style="font-family:sans-serif;padding:12px">${body}<script>${script}</script></body></html>`;

export const works = [
  {
    id: 'sample-fraction-pizza',
    title: '분수 피자 게임',
    type: 'html',
    artifactType: 'html',
    domain: 'lesson',
    category: 'subject_activity',
    subcategory: 'game',
    schoolLevel: 'elementary',
    grade: '4',
    subject: '수학',
    area: '수와 연산',
    unit: '분수',
    topic: '분수의 뜻',
    standard: '[4수01-12]',
    estimatedMinutes: 10,
    groupType: 'individual',
    audience: ['student'],
    tags: ['분수', '게임', '개별활동'],
    description: '피자를 나누며 분수를 배워요.',
    author: '푸른 혹등고래 · 초등',
    howToUse: '피자 조각을 눌러 주어진 분수만큼 색칠해 보세요.',
    promptRecipe: '4학년 분수 도입용 피자 나누기 게임을 만들어 줘. 조각을 누르면 색이 바뀌고 분수가 표시돼.',
    version: 1,
    addedAt: '2026-09-20T00:00:00Z',
    html: page('분수 피자', '<h3>분수 피자</h3><p id="t">8조각 중 0조각</p><button id="b">조각 추가</button>',
      'let n=0;document.getElementById("b").onclick=()=>{n=Math.min(8,n+1);document.getElementById("t").textContent="8조각 중 "+n+"조각 ("+n+"/8)"}'),
  },
  {
    id: 'sample-times-quiz',
    title: '구구단 번개 퀴즈',
    type: 'html',
    artifactType: 'html',
    domain: 'lesson',
    category: 'subject_activity',
    subcategory: 'practice',
    schoolLevel: 'elementary',
    grade: '4',
    subject: '수학',
    topic: '곱셈 복습',
    standard: '[4수01-05]',
    estimatedMinutes: 5,
    groupType: 'individual',
    audience: ['student'],
    tags: ['퀴즈', '연습'],
    description: '무작위 구구단 문제로 곱셈을 빠르게 연습해요.',
    author: '노을 고래 · 초등',
    howToUse: '문제를 보고 답을 입력한 뒤 확인을 누르세요.',
    promptRecipe: '구구단 문제를 무작위로 내고 정답이면 칭찬해 주는 퀴즈를 만들어 줘.',
    version: 1,
    addedAt: '2026-09-22T00:00:00Z',
    html: page('구구단 퀴즈', '<p id="q"></p><input id="a" type="number" aria-label="답"><button id="c">확인</button><p id="r"></p>',
      'let x,y;function nq(){x=2+Math.floor(Math.random()*8);y=2+Math.floor(Math.random()*8);document.getElementById("q").textContent=x+" × "+y+" = ?"}nq();document.getElementById("c").onclick=()=>{document.getElementById("r").textContent=+document.getElementById("a").value===x*y?"정답!":"다시 해 봐요";nq()}'),
  },
  {
    id: 'sample-mult-cards',
    title: '곱셈 연습 카드',
    type: 'html',
    artifactType: 'html',
    domain: 'lesson',
    category: 'subject_activity',
    subcategory: 'practice',
    schoolLevel: 'elementary',
    grade: '4',
    subject: '수학',
    topic: '세 자리 수의 곱셈',
    standard: '[4수01-07]',
    estimatedMinutes: 10,
    groupType: 'pair',
    audience: ['student'],
    tags: ['연습', '모둠활동'],
    description: '짝과 카드를 뒤집으며 곱셈을 연습해요.',
    author: '새벽 고래 · 초등',
    howToUse: '카드를 눌러 뒤집으며 곱셈을 연습하세요.',
    promptRecipe: '곱셈 연습용 뒤집기 카드를 만들어 줘.',
    version: 1,
    addedAt: '2026-09-25T00:00:00Z',
    html: page('곱셈 카드', '<div id="c" style="padding:24px;border:1px solid #888;cursor:pointer">12 × 3 (눌러서 정답 보기)</div>',
      'document.getElementById("c").onclick=function(){this.textContent="36"}'),
  },
  {
    id: 'sample-water-states',
    title: '물의 상태 변화 관찰',
    type: 'html',
    artifactType: 'html',
    domain: 'lesson',
    category: 'subject_activity',
    subcategory: 'simulation',
    schoolLevel: 'middle',
    grade: '1',
    subject: '과학',
    topic: '물질의 상태 변화',
    standard: '[9과03-02]',
    estimatedMinutes: 20,
    groupType: 'whole_class',
    audience: ['teacher', 'student'],
    tags: ['탐구', '시뮬레이션'],
    description: '온도를 바꾸며 물의 세 가지 상태를 관찰해요.',
    author: '바다빛 고래 · 중등',
    howToUse: '슬라이더로 온도를 바꿔 물의 상태를 관찰하세요.',
    promptRecipe: '온도 슬라이더로 물의 고체·액체·기체 상태가 바뀌는 시뮬레이터를 만들어 줘.',
    version: 1,
    addedAt: '2026-09-27T00:00:00Z',
    html: page('물의 상태', '<input id="s" type="range" min="-20" max="120" value="20" aria-label="온도"><p id="o"></p>',
      'const s=document.getElementById("s"),o=document.getElementById("o");function u(){const t=+s.value;o.textContent=t+"℃ : "+(t<=0?"고체(얼음)":t<100?"액체(물)":"기체(수증기)")}s.oninput=u;u()'),
  },
  {
    id: 'sample-class-timer',
    title: '교실 모래시계 타이머',
    type: 'html',
    artifactType: 'html',
    domain: 'lesson',
    category: 'classroom_tool',
    subcategory: 'timer',
    estimatedMinutes: 5,
    groupType: 'teacher',
    audience: ['teacher'],
    tags: ['타이머', '전체활동'],
    description: '활동 시간을 크게 보여 주는 교실용 타이머예요.',
    author: '파도 고래 · 초등',
    howToUse: '분을 고르고 시작을 누르면 남은 시간이 크게 보여요.',
    promptRecipe: '전자칠판에 크게 보이는 수업용 타이머를 만들어 줘. 분을 고르고 시작·멈춤 버튼이 있어.',
    version: 1,
    addedAt: '2026-09-10T00:00:00Z',
    html: page('교실 타이머', '<select id="m"><option>1</option><option selected>3</option><option>5</option></select>분 <button id="s">시작</button><p id="t" style="font-size:48px">03:00</p>',
      'let left=0,iv;const t=document.getElementById("t");function draw(){t.textContent=String(Math.floor(left/60)).padStart(2,"0")+":"+String(left%60).padStart(2,"0")}document.getElementById("s").onclick=()=>{clearInterval(iv);left=+document.getElementById("m").value*60;draw();iv=setInterval(()=>{left=Math.max(0,left-1);draw();if(!left)clearInterval(iv)},1000)}'),
  },
  {
    id: 'sample-csv-summary',
    title: '설문 CSV 응답 집계기',
    type: 'html',
    artifactType: 'html',
    domain: 'work',
    category: 'automation',
    subcategory: 'spreadsheet',
    audience: ['teacher', 'admin'],
    tags: ['자동화', '설문', '통계'],
    description: '설문 결과 CSV를 붙여 넣으면 문항별 응답 수를 세어 줘요. 데이터는 밖으로 나가지 않아요.',
    author: '물결 고래 · 중등',
    howToUse: 'CSV 내용을 붙여 넣고 집계를 누르세요. 첫 줄은 문항 이름이어야 해요.',
    promptRecipe: 'CSV를 붙여 넣으면 열마다 값별 개수를 표로 보여 주는 집계 도구를 만들어 줘. 외부 전송 없이.',
    version: 1,
    addedAt: '2026-09-12T00:00:00Z',
    html: page('CSV 집계', '<textarea id="c" rows="6" cols="40" aria-label="CSV"></textarea><br><button id="b">집계</button><pre id="o"></pre>',
      'document.getElementById("b").onclick=()=>{const rows=document.getElementById("c").value.trim().split(/\\n/).map(r=>r.split(","));const head=rows.shift()||[];document.getElementById("o").textContent=head.map((h,i)=>{const n={};rows.forEach(r=>{const v=(r[i]||"").trim();n[v]=(n[v]||0)+1});return h+": "+Object.entries(n).map(([k,v])=>k+" "+v).join(", ")}).join("\\n")}'),
  },
];

export const exeItems = [
  {
    id: 'sample-exe-coding-tool',
    title: '블록 코딩 연습 도구 (설치형)',
    type: 'exe-link',
    artifactType: 'exe',
    domain: 'lesson',
    category: 'project',
    subcategory: 'coding',
    schoolLevel: 'middle',
    grade: '1',
    subject: '정보',
    standard: '[9정01-01]',
    audience: ['teacher'],
    tags: ['코딩'],
    description: '교사 PC에 설치해 쓰는 블록 코딩 시연 도구(테스트 데이터).',
    author: '은빛 고래 · 중등',
    howToUse: '교사 PC에 설치한 뒤 수업 시연에 사용합니다.',
    version: 1,
    addedAt: '2026-09-28T00:00:00Z',
    url: 'https://example.com/downloads/block-coding.exe',
    sourceRepo: 'https://example.com/source/block-coding',
    sha256: 'a'.repeat(64),
    scanResult: '샘플: 검사 통과 (테스트 데이터)',
    environment: 'Windows 10 이상',
  },
];
