// 화면 문구 모음 — 고래 용어는 짧은 설명과 함께 쓴다. 디자인 교체 때도 문구는 여기서만 고친다.
export const S = {
  appName: '고래곳간',
  tagline: '만들고 끝나는 바이브코딩을, 이어 쓰는 수업으로.',
  oneLine: '교실에서 만든 바이브코딩 작품을 안전하게 이어 쓰는 웨일 사이드패널',
  tabs: { catalog: '큰 곳간', market: '나눔 곳간', mypod: '내 곳간', class: '학급 꾸러미' },
  tabHints: { catalog: '검수된 작품', market: '모두가 올린 작품', mypod: '내 기기에만 저장', class: '교사고래 전용' },
  mode: {
    baby: '학생고래 모드',
    mother: '교사고래 모드',
    toggleToMother: '교사고래 모드로',
    toggleToBaby: '학생고래 모드로',
    on: '교사고래 모드로 바꿨어요. 학생 앞에서는 위쪽 띠 색을 확인하세요.',
  },
  badge: {
    clear: '🟢 맑은 바다 (학생 사용 가능)',
    shallow: '🟡 얕은 바다 (교사용 또는 미검수)',
    whirlpool: '🔴 소용돌이 (보류)',
  },
  pick: '🐋 고래 픽 (파수꾼이 찜했어요)',
  tailprintOk: (name, date) => `검수 서명 확인됨 · 파수꾼 ${name} · ${date}`,
  reason: {
    NO_TAILPRINT: '검수 서명이 없어요',
    CONTENT_CHANGED: '서명 뒤 내용이 바뀌었어요',
    REVIEWER_UNKNOWN: '고래 족보에 없는 검수 서명이에요',
    REVIEWER_REVOKED: '말소된 검수 서명이라 배지를 표시하지 않아요',
    SIG_INVALID: '검수 서명이 맞지 않아요',
    LIST_INVALID: '고래 족보(파수꾼 명부)를 확인할 수 없어 배지 확인이 불가능해요',
    LIST_OLD: '이미 본 것보다 오래된 고래 족보예요',
  },
  source: { maker: '직접 만듦', catalog: '큰 곳간에서 담음', bundle: '꾸러미', link: '바로 실행 링크' },
  listState: {
    network: '최신 목록',
    cache: '오프라인 목록 (마지막으로 받은 목록)',
    sample: '샘플 목록 (아직 공개 주소가 없어요)',
    listRejected: '새 고래 족보가 오래되어 이전 족보를 계속 써요',
  },
  filter: {
    grade: '학년', subject: '교과', badge: '배지', all: '전체',
    pickOnly: '🐋 고래 픽만',
    sort: { label: '정렬', pick: '고래 픽 먼저', new: '새로 들어옴', spout: '물뿜기 많은 순' },
  },
  empty: {
    catalog: '조건에 맞는 작품이 없어요.',
    mypod: '큰 곳간에서 담아 보세요.',
    class: '학급 꾸러미는 교사고래 모드에서 쓸 수 있어요. (8단계에서 구현)',
  },
  actions: {
    run: '실행', add: '내 곳간에 담기', remove: '삭제', back: '← 돌아가기', openTab: '새 탭에서 열기',
    create: '만들기', import: '가져오기', edit: '수정', remix: '리믹스', save: '내 곳간에 저장', details: '자세히', close: '접기',
  },
  detail: { howTo: '사용 방법', recipe: '프롬프트 레시피', check: '자동 점검', checkOk: '걸린 항목이 없어요' },
  run: {
    NOT_HTML: '이 작품은 패널 안에서 실행할 수 없어요.',
    NOT_HTTPS: '주소가 https가 아니라서 열 수 없어요.',
    UNSUPPORTED: '이 종류의 작품은 지금 열 수 없어요.',
    WHIRLPOOL: '소용돌이(보류) 작품은 실행할 수 없어요.',
    confirmTitle: '외부 사이트를 새 탭에서 열까요?',
    confirmHost: (host) => `외부 웹앱입니다. 고래곳간 밖의 사이트(${host})에서 열려요. 격리 실행이 아니라서 사이트가 하는 일은 고래곳간이 막을 수 없어요.`,
    confirmUnverified: '검수 서명이 없는 미검수 작품이에요.',
    confirmOpen: '새 탭에서 열기', confirmCancel: '취소',
    running: '격리된 공간에서 실행 중이에요 (외부 통신 차단)',
    openedTab: (t) => `‘${t}’을(를) 새 창에서 열었어요.`,
    ticketGone: '실행할 작품을 찾을 수 없어요. 사이드바에서 [실행]을 다시 눌러 주세요.',
    external: '외부 사이트입니다. 새 탭에서 열려요.',
  },
  add: { done: '내 곳간에 담았어요.', dup: '이미 내 곳간에 있어요.', warn: (n) => `점검에서 ${n}개 항목이 걸렸어요. 얕은 바다(미검수)로 표시돼요.` },
  create: {
    title: '작품 만들기', name: '제목', kind: '종류', kindHtml: 'HTML 붙여넣기/파일', kindUrl: '외부 주소(https)',
    html: 'HTML', file: '.html 파일 (1MB 이하)', url: '주소', grade: '학년', subject: '교과', standard: '성취기준 코드 (선택)',
    minutes: '활동 시간(분, 선택)',
    author: '별명 · 학교급 (예: 푸른 고래 · 초등)', howTo: '사용 방법', recipe: '프롬프트 레시피 (선택)',
    privacyNote: '이름·학교명·연락처는 쓰지 마세요. 별명과 학교급만 써요.',
    saved: '저장했어요.', checkTitle: '자동 점검 결과',
  },
  bundle: {
    exportTitle: '꾸러미로 내보내기 (작품 1~10개를 골라 주세요)',
    packName: '꾸러미 이름', exportBtn: '꾸러미 만들기', saveFile: '파일로 저장', copy: '복사', copied: '복사했어요.',
    madeN: (n, file) => `작품 ${n}개를 꾸러미(${file})로 만들었어요.`,
    pickFirst: '내보낼 작품을 먼저 골라 주세요.', tooMany: '꾸러미에는 작품을 10개까지 담을 수 있어요.',
    importTitle: '꾸러미 가져오기', importHint: '.gorae.json 파일을 고르거나 내용을 붙여 넣어 주세요.', pasteLabel: '꾸러미 내용 붙여넣기',
    check: '확인하기', previewTitle: (name, n) => `꾸러미 "${name}" · 작품 ${n}개`, pickWorks: '담을 작품을 골라 주세요. (이미 있는 작품은 건너뛰어요)',
    confirm: '선택한 작품 담기', dup: '이미 내 곳간에 있어요', nonePicked: '담을 작품을 하나 이상 골라 주세요.',
    imported: (a, b) => `작품 ${a}개를 담았어요.${b ? ` (이미 있어서 ${b}개는 건너뜀)` : ''}`,
    notVerified: '얕은 바다(미검수)로 표시돼요',
  },
  classPack: {
    title: '학급 꾸러미 (웨일 클래스로 배포)', needMother: '학급 꾸러미는 교사고래 모드(교사)에서 쓸 수 있어요.',
    steps: '내 곳간에서 작품을 고르고 → 꾸러미를 만든 뒤 → 웨일 클래스 공지·과제에 붙이면 학생이 가져와요.',
    empty: '내 곳간에 작품이 없어요. 큰 곳간에서 담거나 직접 만들어 보세요.',
    name: '학급 꾸러미 이름 (예: 4학년 3반 수학)', note: '학생에게 전할 한마디 (선택)',
    pick: '배포할 작품 (1~10개)', build: '학급 꾸러미 만들기',
    madeN: (n) => `작품 ${n}개로 학급 꾸러미를 만들었어요.`,
    copyAll: '공지 문구 + 꾸러미 한꺼번에 복사', copyNotice: '공지 문구만 복사', copyPack: '꾸러미만 복사', saveFile: '꾸러미 파일로 저장',
    openClass: '웨일 클래스 열기',
    guide: '웨일 클래스 공지·과제 글에 붙여 넣거나, 저장한 파일을 첨부하세요.',
    tooLong: '글이 길어요. 공지에 붙여 넣기가 안 되면 [꾸러미 파일로 저장] 후 파일을 첨부하세요.',
    copied: { all: '공지 문구와 꾸러미를 복사했어요. 웨일 클래스 글에 붙여 넣으세요.', notice: '공지 문구를 복사했어요.', pack: '꾸러미를 복사했어요.' },
    none: '배포할 작품을 먼저 골라 주세요.', tooMany: '학급 꾸러미는 작품을 10개까지 담을 수 있어요.',
    defaultName: '우리 반 꾸러미',
  },
  form: {
    choose: '고르세요', unknown: '모름', yes: '예', no: '아니요',
    step1: '1. 작품 형태', artifactType: '형태', exeMotherOnly: '실행형 프로그램(EXE)은 교사고래 모드(교사)에서만 등록할 수 있어요.',
    step2: '2. 분류 (대표 카테고리는 하나만)', domain: '수업 / 업무', category: '대표 카테고리', subcategory: '하위 카테고리', activityType: '활동 유형',
    oneCategory: '여러 기능이 있어도 대표 카테고리는 하나만 고르고, 나머지는 태그로 적어 주세요.',
    step3detail: '교과 정보', step3lesson: '수업 정보', subjectOptional: '교과 정보 더하기 (선택)',
    schoolLevel: '학교급', grade: '학년', subject: '교과', topic: '주제', topicPh: '예: 분수의 크기 비교', area: '영역 (선택)', unit: '단원 (선택)', lessonNo: '차시 (선택)', standard: '성취기준 (선택)',
    groupType: '활동 형태', time: '예상 시간',
    audience: '대상 사용자 (하나 이상)', audienceHint: '교사와 학생이 함께 쓰면 둘 다 고르세요.',
    step4: '기본 정보', description: '설명 (한두 문장)', descriptionPh: '예: 피자를 나누며 분수를 배워요.',
    tags: '태그 (쉼표로 구분, 아래 추천 태그를 눌러도 돼요)', tagPh: '예: 분수, 게임, 개별활동',
    htmlTitle: 'HTML 작품', htmlHint: '저장 전에 외부 전송·개인정보 입력·API 키·외부 스크립트·위험 동작을 자동으로 점검해요.',
    webappTitle: '웹앱 정보', webappWarn: '외부 웹앱입니다. 고래곳간 밖에서 실행되어 격리 실행이 적용되지 않아요. 검수 여부도 카드에 표시돼요.',
    webappUrl: '웹앱 주소 (https)', sourceUrl: '소스코드 주소 (선택, https)',
    loginRequired: '로그인이 필요한가요?', usesExternalApi: '외부 API를 쓰나요?', mobileSupported: '모바일에서 되나요?', collectsPersonalInfo: '개인정보를 입력받나요?', needsInternet: '인터넷이 꼭 필요한가요?',
    exeTitle: '실행형 프로그램(EXE) 정보', exeWarn: '가장 높은 위험 등급이에요. 고래곳간은 실행 파일을 보관하지 않고 링크와 검사 정보만 기록해요. 검수 서명이 있어야 큰 곳간에 올라가요.',
    exeUrl: '다운로드 링크 (https)', exeSource: '소스 저장소 (https)', shaPh: '64자리 16진수', exeScan: '바이러스 검사 결과', exeEnv: '실행 환경',
  },
  find: {
    search: '찾기 (제목·주제·성취기준·#태그)', more: '자세한 조건', domainAll: '수업 + 업무', categoryAll: '모든 카테고리', subAll: '모든 하위',
    grade: '학교급·학년', audience: '대상', group: '활동 형태', time: '이 시간 안에', tag: '태그', reset: '조건 지우기',
    found: (n, total) => `${total}개 중 ${n}개를 찾았어요.`,
  },
  cardMeta: { webapp: '🌐 외부 웹앱입니다', exe: '⚠️ 실행형 프로그램(EXE)', legacy: '예전 작품 (분류 없음)' },
  pin: {
    setTitle: '교사고래 암호 정하기', setHint: '이 기기에서만 쓰는 4~8자리 숫자예요. 해시로만 저장돼요.',
    enterTitle: '교사고래 암호 (교사)', enterHint: '암호를 넣으면 교사고래 모드(교사)로 바뀌어요.',
    pin: '암호 (숫자 4~8자리)', confirm: '한 번 더', ok: '확인', cancel: '취소',
    FORMAT: '암호는 숫자 4~8자리로 정해 주세요.', MISMATCH: '두 암호가 서로 달라요.',
    WRONG: (left) => `암호가 틀렸어요. (${left}번 더 틀리면 잠시 잠겨요)`,
    LOCKED: (sec) => `여러 번 틀려서 ${sec}초 동안 잠겼어요.`,
    forgot: '암호를 잊었어요', forgotConfirm: '암호를 지우고 학생고래 모드로 돌아갈까요? 다시 정하면 교사고래 모드를 쓸 수 있어요. (내 곳간 작품은 그대로예요)',
    reset: '암호 지우기', resetDone: '암호를 지웠어요. 새로 정해 주세요.',
  },
  spout: {
    counts: (t, s) => `💨 교사 ${t} · 학생 ${s}`,
    button: '💨 물뿜기', done: '💨 뿜었어요',
    hint: '물뿜기는 익명 추천이에요. 이 기기에서 작품마다 한 번만 누를 수 있어요.',
    pending: (n) => `보내지 않은 물뿜기 ${n}개가 이 기기에 있어요.`,
    send: '물뿜기 보내기 (의견 설문)', sent: '폼에 붙여 넣고 제출했어요',
    copiedOpen: '물뿜기 보고를 복사하고 의견 설문을 열었어요. 붙여 넣고 제출한 뒤 아래 [제출했어요]를 눌러 주세요.',
    copiedNoForm: '물뿜기 보고를 복사했어요. 물뿜기를 받을 의견 폼이 아직 없어요. 복사한 글을 파수꾼에게 전해 주세요.',
    thanks: '고마워요! 파수꾼이 집계하면 모두의 카드 숫자에 더해져요.',
    already: '이미 물뿜기를 했어요.',
  },
  featured: { title: '이달의 고래자리', hint: '(대왕고래가 고른 이달의 작품)' },
  lineage: (title) => `이 작품은 ‘${title}’을(를) 리믹스했습니다.`,
  share: {
    title: '웨일 스페이스에 공유 (붙여넣기용으로 복사돼요)',
    kinds: { class: '클래스용 안내 복사', teamboard: '팀보드 전시용 복사', ubt: 'UBT 평가용 복사', space: '웨일 스페이스 공유 글 복사' },
    nowOn: (label) => `지금 화면: ${label}`,
    link: '바로 실행 링크 복사',
    copied: (label) => `${label}을(를) 복사했어요. 붙여 넣기만 하세요.`,
    linkCopied: '바로 실행 링크를 복사했어요.',
    tooBig: '바로 실행 링크로 만들기에는 작품이 큽니다. 꾸러미 파일로 공유해 주세요.',
    tooBigCopied: '링크는 만들 수 없어 꾸러미 파일 안내가 들어간 글을 복사했어요.',
    hint: '웨일 서비스 화면을 고래곳간이 직접 건드리지 않아요. 복사한 글을 붙여 넣어 주세요.',
  },
  submit: {
    title: '나눔 곳간에 공유하기 (구글 폼 + 드라이브)',
    nickname: '닉네임 (실명 말고 별명)', comment: '한 마디 (선택)', privacy: '작품 안에 학생 이름·사진·연락처가 없어요.',
    prepare: '공유 준비하기',
    step1: (name) => `① 업로드할 파일 저장 (${name})`,
    step2: '② 구글 폼 열기 (닉네임·제목·종류·설명 자동 채움)',
    step3: '③ 폼에서 저장한 파일을 올리고 제출하면 나눔 곳간 목록에 올라가요. (파일 올리기는 구글 로그인이 필요해요)',
    noFile: '웹앱·실행 파일은 파일 없이 주소 칸이 자동으로 채워져요.',
    notReady: '운영자가 아직 구글 폼을 연결하지 않았어요. 아래 값을 폼에 직접 넣어 주세요.',
    field: { nickname: '1. 닉네임', title: '2. 앱 제목', kind: '3. 앱 종류', description: '4. 설명', format: '5. 자료 종류', address: '웹 앱 주소' },
    copy: '복사', copied: '복사했어요.',
    songLabel: '고래 노래 (한 줄 후기, 80자 이하)', song: '고래 노래 보내기',
    songCopied: '고래 노래를 복사했어요.', songNoForm: '고래 노래를 받을 의견 설문이 아직 없어요. 복사한 글을 파수꾼에게 전해 주세요.',
  },
  market: {
    title: '나눔 곳간', hint: '선생님과 학생이 구글 폼으로 올린 작품이에요. 검수 전이라 모두 얕은 바다(미검수)예요.',
    kind: '앱 종류', refresh: '새로고침', import: '가져오기', importing: '가져오는 중…', imported: '내 곳간에 담음',
    loading: '목록을 불러오는 중이에요…', empty: '아직 올라온 작품이 없어요.', none: '조건에 맞는 작품이 없어요.',
    count: (n) => `작품 ${n}개`, cache: '인터넷이 안 돼서 마지막으로 받은 목록을 보여 줘요.',
    by: (nick, whale) => [nick, whale].filter(Boolean).join(' · '),
    added: (titles) => `‘${titles.join('’, ‘')}’을(를) 내 곳간에 담았어요.`, dup: (titles) => `이미 내 곳간에 있어요: ${titles.join(', ')}`,
    columns: (missing, header) => `시트에서 필요한 열(${missing.join(', ')})을 찾지 못했어요. 지금 시트의 열: ${header.join(' | ')}`,
    error: {
      NOT_CONFIGURED: '운영자가 아직 나눔 곳간 시트를 연결하지 않았어요. (config: market-config.js)',
      PRIVATE: '시트나 파일이 공개되어 있지 않아요. 운영자는 시트·드라이브 폴더를 "링크가 있는 모든 사용자 - 뷰어"로 공유해 주세요.',
      NETWORK: '인터넷 연결을 확인해 주세요.', TIMEOUT: '응답이 너무 늦어요. 잠시 뒤 새로고침해 주세요.',
      TOO_BIG: '파일이 너무 커요(2MB 초과).', BAD_URL: '구글 드라이브 파일 주소가 아니에요.', BAD_REDIRECT: '안전하지 않은 곳으로 이동해서 멈췄어요.',
      HTTP: '파일을 받지 못했어요.', INVALID: '고래곳간 작품 파일이 아니라 저장하지 않았어요.',
    },
    runTitle: '나눔 곳간에서 가져온 작품이에요', runBody: '검수 서명이 없는 작품이에요. 격리된 창에서 외부 통신 없이 실행돼요. 실행할까요?',
    runOk: '실행', runCancel: '취소',
  },
  edit: {
    titleEdit: '작품 수정', titleRemix: '리믹스', remixHint: '원본의 내용과 프롬프트 레시피를 복사했어요. 새 작품은 미검수로 시작해요.',
    separate: '큰 곳간·꾸러미 작품은 원본을 그대로 두고 "내 수정본(미검수)"으로 따로 저장했어요.',
    versionUp: (v) => `버전 ${v}으로 저장했어요.`, remixSaved: '리믹스를 저장했어요. 새 작품은 미검수예요.',
    editedFrom: '내 수정본', remixOfLabel: '리믹스 원본',
  },
  grades: ['초1', '초2', '초3', '초4', '초5', '초6', '중1', '중2', '중3', '고1', '고2', '고3'],
  subjects: ['국어', '수학', '사회', '과학', '영어', '정보', '미술', '음악', '체육', '도덕', '기타'],
};
